const test=require('node:test'),assert=require('node:assert/strict');
const baseline='de3a19d0ef1f6dbed9659e9bc42616a20b07fd4c';
test('real goal162: net first, two wall seconds at all rates, same queue and no clock/engine debt',async()=>{
 const {setup,seek}=await import('../tools/match3d-round2-audit.mjs');
 for(const speed of [.5,1,2]){const h=setup();seek(h,1,162);h.run(`setMatchSpeed(${speed});for(let i=0;i<1000&&!pitchV73.goalPresentation;i++){qaWall+=.02;ManagerStoryLive3D.step(.02,qaWall*1000)}if(!pitchV73.goalPresentation)throw Error('No real goal presentation');`);
 const net=h.run('({time:ManagerStoryLive3D.time,impact:structuredClone(pitchV73.netImpact),state:structuredClone(pitchV73.goalPresentation),ball:[...pitchV73.ball],positions:JSON.stringify(pitchV73.positions),events:JSON.stringify(M.events),queue:JSON.stringify(pitchV73.queue)})');assert.equal(net.impact.eventId,162);assert.ok(net.state.netUntil>=net.impact.seconds+.35-1e-8);
 h.run('for(let i=0;i<100&&!pitchV73.goalFeedback?.visible;i++){qaWall+=.02;ManagerStoryLive3D.step(.02,qaWall*1000)}');const hold=h.run('({time:ManagerStoryLive3D.time,until:pitchV73.goalPresentation.until,now:qaWall*1000,queue:JSON.stringify(pitchV73.queue),match:pitchV73.displayMatchSeconds,feedback:structuredClone(pitchV73.goalFeedback)})');assert.equal(hold.feedback.visible,true);assert.equal(hold.until-hold.now,2000);assert.equal(hold.queue,net.queue);assert.deepEqual(h.run('pitchV73.ball'),net.ball);
 h.run('qaWall+=1.99;ManagerStoryLive3D.step(1.99,qaWall*1000)');assert.equal(h.run('ManagerStoryLive3D.time'),hold.time);assert.equal(h.run('pitchV73.displayMatchSeconds'),hold.match);assert.equal(h.run('JSON.stringify(M.events)'),net.events);assert.equal(h.run('JSON.stringify(pitchV73.positions)'),net.positions);assert.equal(h.run('JSON.stringify(pitchV73.queue)'),hold.queue);
 h.run('pauseLive();ManagerStoryLive3D.step(10,qaWall*1000+10000);setMatchView("2d");setMatchView("3d")');assert.equal(h.run('ManagerStoryLive3D.time'),hold.time);assert.equal(h.run('pitchV73.goalFeedback.visible'),true);h.run('resumeLive();qaWall+=.011;ManagerStoryLive3D.step(.011,qaWall*1000)');assert.equal(h.run('pitchV73.goalPresentation'),null);assert.equal(h.run('ManagerStoryLive3D.time'),hold.time);h.run('qaWall+=.02;ManagerStoryLive3D.step(.02,qaWall*1000)');assert.ok(Math.abs(h.run('ManagerStoryLive3D.time')-hold.time-.02*speed/2)<1e-8);
 }
});
test('two matches preserve engine/RNG/career, half/final drain and one result application',async()=>{const {setup,full}=await import('../tools/match3d-round2-audit.mjs');for(const seed of [1,8800]){const before=full(setup(true,baseline),seed),after=full(setup(),seed);assert.equal(after.raw,before.raw);assert.equal(after.career,before.career);assert.ok(after.finished&&!after.pending&&after.singleResult);console.log('engine equality',seed,after.events.length);}});

test('finish requested during real goal waits for image, then drains once under delayed frames',async()=>{const {setup,seek}=await import('../tools/match3d-round2-audit.mjs');const h=setup();seek(h,1,162);h.run('finalizeMatch();for(let i=0;i<3000&&!pitchV73.goalFeedback?.visible;i++){qaWall+=2;ManagerStoryLive3D.step(2,qaWall*1000)}');assert.equal(h.run('pitchV73.goalFeedback.visible'),true);assert.equal(h.run('ManagerStoryLive3D.finishing'),true);h.run('for(let i=0;i<3000&&ManagerStoryLive3D.finishing;i++){qaWall+=2;ManagerStoryLive3D.step(2,qaWall*1000)}');assert.equal(h.run('ManagerStoryLive3D.finishing'),false);assert.equal(h.run('M.events.filter(e=>e.type==="end").length'),1);});
